import { defineConfig } from 'tsdown'

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/service.ts',
    'src/recovery-coordinator.ts',
    'src/commands.ts',
    'src/tools.ts',
    'src/memory.ts',
    'src/tool-memory.ts',
    'src/prompt-artifacts.ts',
    'src/prompt-rules.ts',
    'src/custom-commands.ts',
    'src/team-service.ts',
    'src/team-state.ts',
    'src/team-store.ts',
    'src/tool-team.ts',
    'src/ralph-service.ts',
    'src/ralph-state.ts',
    'src/ralph-store.ts',
    'src/tool-ralph.ts',
    'src/delivery-service.ts',
    'src/delivery-state.ts',
    'src/delivery-store.ts',
    'src/tool-delivery.ts',
    'src/code-intelligence.ts',
    'src/notification-service.ts',
    'src/notification-state.ts',
    'src/notification-store.ts',
    'src/skill-mcp.ts',
    'src/visual-qa.ts',
    'src/workflow-service.ts',
    'src/workflow-state.ts',
    'src/workflow-store.ts',
    'src/tool-workflow.ts',
    'src/mission-service.ts',
    'src/mission-state.ts',
    'src/mission-store.ts',
    'src/tool-mission.ts',
    'src/lifecycle-hooks.ts',
    'src/specialist-catalog.ts',
    'src/specialist-runner.ts',
    'src/run-dashboard.ts',
    'src/run-dashboard-service.ts',
    'src/skills.ts',
    'src/doctor.ts',
  ],
  outDir: 'lib',
  format: ['esm'],
  platform: 'node',
  target: 'es2024',
  fixedExtension: false,
  dts: true,
  clean: true,
  deps: { neverBundle: [/^@deepseek-ai\//u, /^@ast-grep\//u, /^playwright/u] },
})
